#include "catch2/catch.hpp"
#include "CryptoCom/ElGamal.h"

#include <limits>


using namespace CryptoCom;

TEST_CASE("Keys are generated by scrambling a random number with modulo exponent") {
  constexpr auto const SecretNumber = 79;
  auto rng = std::function<int()>{[SecretNumber](){ return SecretNumber; }};
  auto const keys = ElGamal::ElGamal::GenerateKeys(8009, 1131, rng);
  REQUIRE(keys == std::make_pair(SecretNumber, 7697));
}