name: Continuous Integration
on: [push, pull_request]

jobs:
  build-linux:
    name: Build on Linux
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install system dependencies
        run: sudo apt-get install -y cmake ninja-build

      - name: Install Conan
        run: pip install 'conan>=2.0'

      - name: Generate default profile
        run: conan profile detect

      - name: Install project dependencies
        run: conan install . --build=missing -s build_type=Release

      - name: Configure
        run: cmake --preset release

      - name: Unit tests
        run: cmake --build --preset release

      - name: Integration Tests
        run: cmake --build --preset release-integration