name: Continuous Integration
on: [push, pull_request]

jobs:
  build-linux:
    name: Build on Linux
    runs-on: ubuntu-latest
    env:
      PATH: /home/runner/.local/bin:/usr/share/rust/.cargo/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/snap/bin
    steps:
      - uses: actions/checkout@v1
        with:
          fetch-depth: 1

      - name: Install dependencies
        run: |
          echo $PATH
          python -m pip install --upgrade pip
          python -m pip install --user 'cmake==3.15.3' 'ninja==1.9.0'
      
      - name: Configure
        run: cmake -Bbuild -GNinja .
      
      - name: Integration Test
        run: cmake --build build -t check-integration -v